version: "3.8"
services:
  app:
    image: tnydevdocs/aiservice:latest
    container_name: ai-service
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    volumes:
      - ./certs:/app/certs:ro
    restart: unless-stopped

networks:
  gym-rag-network:
    driver: bridge
