version: "3.8"

services:
  backend:
    container_name: gym-rag-service
    image: tnydevdocs/aiservice:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    volumes:
      - ./certs:/certs:ro
    networks:
      - gym-health-tech

networks:
  gym-health-tech:
    driver: bridge
